name: nmme_workflow_env
channels:
  - conda-forge
  - iri-nextgen
  - defaults
dependencies:
  - python=3.12
  - cartopy
  - cftime
  - dask
  - ftputil
  - geocat-viz
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pyyaml
  - s3fs
  - scipy
  - scikit-learn
  - statsmodels
  - xarray
  - zarr
  - pip
  - pip:
    - arraylake>=1.0.0
