name: nmme_workflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - xarray
  - dask
  - cftime
  - netcdf4
  - scipy
  - matplotlib
  - cartopy
  - pyyaml
  - fsspec
  - rasterio
  - geopandas
  - xskillscore
  - jinja2
  - cptbin
  - cptcore
  - cptio
  - cptdl
  - cptextras
  - ipykernel
  - ipython
  - pytest
  - pytest-xdist
  - cffi
  - pip:
      - xarray-spatial
      - zarr
      - leaning
